// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RoomService/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ULZAsset.ProtoMod {

  /// <summary>Holder for reflection information generated from RoomService/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for RoomService/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlSb29tU2VydmljZS9zZXJ2aWNlLnByb3RvEghVTFpQcm90bxoZUm9vbVNl",
          "cnZpY2UvbWVzc2FnZS5wcm90bxoMY29tbW9uLnByb3RvMvwDCgtSb29tU2Vy",
          "dmljZRI3CgpDcmVhdGVSb29tEhcuVUxaUHJvdG8uUm9vbUNyZWF0ZVJlcRoO",
          "LlVMWlByb3RvLlJvb20iABI6CgtHZXRSb29tTGlzdBIXLlVMWlByb3RvLlJv",
          "b21DcmVhdGVSZXEaDi5VTFpQcm90by5Sb29tIgAwARIyCgtHZXRSb29tSW5m",
          "bxIRLlVMWlByb3RvLlJvb21SZXEaDi5VTFpQcm90by5Sb29tIgASNwoKVXBk",
          "YXRlUm9vbRIXLlVMWlByb3RvLlJvb21DcmVhdGVSZXEaDi5VTFpQcm90by5S",
          "b29tIgASOwoPU2VydmVyQnJvYWRjYXN0EhEuVUxaUHJvdG8uUm9vbVJlcRoR",
          "LlVMWlByb3RvLlJvb21Nc2ciADABEjMKC1NlbmRNZXNzYWdlEhEuVUxaUHJv",
          "dG8uUm9vbU1zZxoPLlVMWlByb3RvLkVtcHR5IgASMAoIUXVpdFJvb20SES5V",
          "TFpQcm90by5Sb29tUmVxGg8uVUxaUHJvdG8uRW1wdHkiABI2CglRdWlja1Bh",
          "aXISFy5VTFpQcm90by5Sb29tQ3JlYXRlUmVxGg4uVUxaUHJvdG8uUm9vbSIA",
          "Ei8KCEpvaW5Sb29tEhEuVUxaUHJvdG8uUm9vbVJlcRoOLlVMWlByb3RvLlJv",
          "b20iAEIbWgVwcm90b6oCEVVMWkFzc2V0LlByb3RvTW9kYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ULZAsset.ProtoMod.MessageReflection.Descriptor, global::ULZAsset.ProtoMod.CommonReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code