// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RoomService/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ULZAsset.ProtoMod {

  /// <summary>Holder for reflection information generated from RoomService/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for RoomService/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlSb29tU2VydmljZS9zZXJ2aWNlLnByb3RvEghVTFpQcm90bxoZUm9vbVNl",
            "cnZpY2UvbWVzc2FnZS5wcm90bxoMY29tbW9uLnByb3RvMsAECgtSb29tU2Vy",
            "dmljZRI3CgpDcmVhdGVSb29tEhcuVUxaUHJvdG8uUm9vbUNyZWF0ZVJlcRoO",
            "LlVMWlByb3RvLlJvb20iABI6CgtHZXRSb29tTGlzdBIXLlVMWlByb3RvLlJv",
            "b21DcmVhdGVSZXEaDi5VTFpQcm90by5Sb29tIgAwARIyCgtHZXRSb29tSW5m",
            "bxIRLlVMWlByb3RvLlJvb21SZXEaDi5VTFpQcm90by5Sb29tIgASNwoKVXBk",
            "YXRlUm9vbRIXLlVMWlByb3RvLlJvb21DcmVhdGVSZXEaDi5VTFpQcm90by5S",
            "b29tIgASQQoNQnJvYWRjYXN0SW5mbxIRLlVMWlByb3RvLlJvb21SZXEaGy5V",
            "TFpQcm90by5Sb29tQnJvYWRjYXN0SW5mbyIAEjwKClVwZGF0ZUNhcmQSGy5V",
            "TFpQcm90by5Sb29tVXBkYXRlQ2FyZFJlcRoPLlVMWlByb3RvLkVtcHR5IgAS",
            "MwoLU2VuZE1lc3NhZ2USES5VTFpQcm90by5Sb29tTXNnGg8uVUxaUHJvdG8u",
            "RW1wdHkiABIwCghRdWl0Um9vbRIRLlVMWlByb3RvLlJvb21SZXEaDy5VTFpQ",
            "cm90by5FbXB0eSIAEjYKCVF1aWNrUGFpchIXLlVMWlByb3RvLlJvb21DcmVh",
            "dGVSZXEaDi5VTFpQcm90by5Sb29tIgASLwoISm9pblJvb20SES5VTFpQcm90",
            "by5Sb29tUmVxGg4uVUxaUHJvdG8uUm9vbSIAQhtaBXByb3RvqgIRVUxaQXNz",
            "ZXQuUHJvdG9Nb2RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ULZAsset.ProtoMod.MessageReflection.Descriptor, global::ULZAsset.ProtoMod.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null,  null));
    }
    #endregion

  }
}

#endregion Designer generated code
