// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameDuelService/EventHookPhase.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ULZAsset.ProtoMod.GameDuelService {

  /// <summary>Holder for reflection information generated from GameDuelService/EventHookPhase.proto</summary>
  public static partial class EventHookPhaseReflection {

    #region Descriptor
    /// <summary>File descriptor for GameDuelService/EventHookPhase.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventHookPhaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiRHYW1lRHVlbFNlcnZpY2UvRXZlbnRIb29rUGhhc2UucHJvdG8SCFVMWlBy",
          "b3RvKusDCg5FdmVudEhvb2tQaGFzZRIRCg1nYW1lc2V0X3N0YXJ0EAASFAoQ",
          "c3RhcnRfdHVybl9waGFzZRABEhwKGHJlZmlsbF9hY3Rpb25fY2FyZF9waGFz",
          "ZRACEhgKFG1vdmVfY2FyZF9kcm9wX3BoYXNlEAMSGAoUZGV0ZXJtaW5lX21v",
          "dmVfcGhhc2UQBBIVChFmaW5pc2hfbW92ZV9waGFzZRAFEhYKEmNoYXJhX2No",
          "YW5nZV9waGFzZRAGEiAKHGRldGVybWluZV9jaGFyYV9jaGFuZ2VfcGhhc2UQ",
          "BxIaChZhdHRhY2tfY2FyZF9kcm9wX3BoYXNlEAgSGwoXZGVmZW5jZV9jYXJk",
          "X2Ryb3BfcGhhc2UQCRIgChxkZXRlcm1pbmVfYmF0dGxlX3BvaW50X3BoYXNl",
          "EAoSFwoTYmF0dGxlX3Jlc3VsdF9waGFzZRALEhAKDGRhbWFnZV9waGFzZRAM",
          "EhsKF2RlYWRfY2hhcmFfY2hhbmdlX3BoYXNlEA0SJQohZGV0ZXJtaW5lX2Rl",
          "YWRfY2hhcmFfY2hhbmdlX3BoYXNlEA4SGwoXY2hhbmdlX2luaXRpYXRpdmVf",
          "cGhhc2UQDxIVChFmaW5pc2hfdHVybl9waGFzZRAQEg8KC2dhbWVzZXRfZW5k",
          "EBEqPgoNRXZlbnRIb29rVHlwZRILCgdJbnN0YW50EAASCgoGQmVmb3JlEAES",
          "CQoFUHJveHkQAhIJCgVBZnRlchADQi1aBy47cHJvdG+qAiFVTFpBc3NldC5Q",
          "cm90b01vZC5HYW1lRHVlbFNlcnZpY2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new [] { typeof(global::ULZAsset.ProtoMod.GameDuelService.EventHookPhase), typeof(global::ULZAsset.ProtoMod.GameDuelService.EventHookType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ----------------------------------------------------
  /// ANCHOR EventHookPhase.proto
  /// SECTION: EventHookPhase.proto
  /// </summary>
  public enum EventHookPhase {
    /// <summary>
    /// start gameset
    /// </summary>
    [pbr::OriginalName("gameset_start")] GamesetStart = 0,
    /// <summary>
    /// -- turn lifecycle
    /// </summary>
    [pbr::OriginalName("start_turn_phase")] StartTurnPhase = 1,
    /// <summary>
    /// ---- Draw phase (ddp)
    /// </summary>
    [pbr::OriginalName("refill_action_card_phase")] RefillActionCardPhase = 2,
    /// <summary>
    ///   refill_event_card_phase                        = 3;
    /// ---- Move phase
    /// </summary>
    [pbr::OriginalName("move_card_drop_phase")] MoveCardDropPhase = 3, [pbr::OriginalName("determine_move_phase")] DetermineMovePhase = 4, [pbr::OriginalName("finish_move_phase")] FinishMovePhase = 5, [pbr::OriginalName("chara_change_phase")] CharaChangePhase = 6, [pbr::OriginalName("determine_chara_change_phase")] DetermineCharaChangePhase = 7,
    /// <summary>
    /// ---- Atk/Def Phase 
    /// </summary>
    [pbr::OriginalName("attack_card_drop_phase")] AttackCardDropPhase = 8, [pbr::OriginalName("defence_card_drop_phase")] DefenceCardDropPhase = 9, [pbr::OriginalName("determine_battle_point_phase")] DetermineBattlePointPhase = 10,
    /// <summary>
    ///roll dice
    /// </summary>
    [pbr::OriginalName("battle_result_phase")] BattleResultPhase = 11, [pbr::OriginalName("damage_phase")] DamagePhase = 12,
    /// <summary>
    /// --- Any Raise Phase
    /// </summary>
    [pbr::OriginalName("dead_chara_change_phase")] DeadCharaChangePhase = 13, [pbr::OriginalName("determine_dead_chara_change_phase")] DetermineDeadCharaChangePhase = 14, [pbr::OriginalName("change_initiative_phase")] ChangeInitiativePhase = 15,
    /// <summary>
    //// -- endof turn lifecycle
    /// </summary>
    [pbr::OriginalName("finish_turn_phase")] FinishTurnPhase = 16,
    /// <summary>
    //// endof game set
    /// </summary>
    [pbr::OriginalName("gameset_end")] GamesetEnd = 17,
  }

  public enum EventHookType {
    [pbr::OriginalName("Instant")] Instant = 0, [pbr::OriginalName("Before")] Before = 1, [pbr::OriginalName("Proxy")] Proxy = 2, [pbr::OriginalName("After")] After = 3,
  }

  #endregion

}

#endregion Designer generated code