// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameDuelService/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ULZAsset.ProtoMod.GameDuelService {

  /// <summary>Holder for reflection information generated from GameDuelService/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for GameDuelService/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1HYW1lRHVlbFNlcnZpY2Uvc2VydmljZS5wcm90bxIIVUxaUHJvdG8aHUdh",
          "bWVEdWVsU2VydmljZS9tZXNzYWdlLnByb3RvGgxjb21tb24ucHJvdG8aGkdh",
          "bWVEdWVsU2VydmljZS9EYXRhLnByb3RvMuEHCg9HYW1lRHVlbFNlcnZpY2US",
          "RgoPU2VydmVyQnJvYWRjYXN0EhYuVUxaUHJvdG8uR0RHZXRJbmZvUmVxGhku",
          "VUxaUHJvdG8uR0RCcm9hZGNhc3RSZXNwMAESOgoKQ3JlYXRlR2FtZRIVLlVM",
          "WlByb3RvLkdEQ3JlYXRlUmVxGhUuVUxaUHJvdG8uR2FtZURhdGFTZXQSPAoL",
          "R2V0R2FtZURhdGESFi5VTFpQcm90by5HREdldEluZm9SZXEaFS5VTFpQcm90",
          "by5HYW1lRGF0YVNldBIyCghRdWl0R2FtZRIVLlVMWlByb3RvLkdEQ3JlYXRl",
          "UmVxGg8uVUxaUHJvdG8uRW1wdHkSOwoQSW5zdFNldEV2ZW50Q2FyZBIWLlVM",
          "WlByb3RvLkdESW5zdGFuY2VEVBoPLlVMWlByb3RvLkVtcHR5EjsKEERyYXdQ",
          "aGFzZUNvbmZpcm0SFi5VTFpQcm90by5HREdldEluZm9SZXEaDy5VTFpQcm90",
          "by5FbXB0eRI/ChBNb3ZlUGhhc2VDb25maXJtEhouVUxaUHJvdG8uR0RNb3Zl",
          "Q29uZmlybVJlcRoPLlVMWlByb3RvLkVtcHR5EkYKD01vdmVQaGFzZVJlc3Vs",
          "dBIWLlVMWlByb3RvLkdER2V0SW5mb1JlcRobLlVMWlByb3RvLkdETW92ZUNv",
          "bmZpcm1SZXNwEjsKDkFEUGhhc2VDb25maXJtEhguVUxaUHJvdG8uR0RBRENv",
          "bmZpcm1SZXEaDy5VTFpQcm90by5FbXB0eRJBCg1BRFBoYXNlUmVzdWx0EhYu",
          "VUxaUHJvdG8uR0RHZXRJbmZvUmVxGhguVUxaUHJvdG8uR0RBRFJlc3VsdFJl",
          "c3ASRQoRQURQaGFzZURpY2VSZXN1bHQSFi5VTFpQcm90by5HREdldEluZm9S",
          "ZXEaGC5VTFpQcm90by5HREFERGljZVJlc3VsdBJDChJDaGFuZ2VQaGFzZUNv",
          "bmZpcm0SHC5VTFpQcm90by5HRENoYW5nZUNvbmZpcm1SZXEaDy5VTFpQcm90",
          "by5FbXB0eRI8ChFDaGFuZ2VQaGFzZVJlc3VsdBIWLlVMWlByb3RvLkdER2V0",
          "SW5mb1JlcRoPLlVMWlByb3RvLkVtcHR5EkEKEUV2ZW50UGhhc2VDb25maXJt",
          "EhsuVUxaUHJvdG8uR0RQaGFzZUNvbmZpcm1SZXEaDy5VTFpQcm90by5FbXB0",
          "eRJIChBFdmVudFBoYXNlUmVzdWx0EhYuVUxaUHJvdG8uR0RHZXRJbmZvUmVx",
          "GhwuVUxaUHJvdG8uR0RQaGFzZUNvbmZpcm1SZXNwQi1aBy47cHJvdG+qAiFV",
          "TFpBc3NldC5Qcm90b01vZC5HYW1lRHVlbFNlcnZpY2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ULZAsset.ProtoMod.GameDuelService.MessageReflection.Descriptor, global::ULZAsset.ProtoMod.CommonReflection.Descriptor, global::ULZAsset.ProtoMod.GameDuelService.DataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code