# ULZ Account Service
CredService:
  Connector: grpc
  Host: "192.168.0.110"
  Port: 12000
  Database: ""
  Username: "user1"
  Password: "1234"
  Key: ""
  KeyPemPath: "%StreamAsset%/key.pem"

RoomService:
  ServiceName: "ULZ.RmSvc"
  Connector: grpc
  Host: "192.168.0.110"
  Port: 11000
  Database: ""
  Username: "user1"
  Password: "1234"
  Key: ""
  KeyPemPath: ""
  StreamSetting:
    Connector: nats
    Host: "192.168.0.110"
    Port: 4222

GameDuelService:
  ServiceName: "ULZ.GDSvc"
  Connector: grpc
  Host: "192.168.0.110"
  Port: 13000
  Database: ""
  Username: "user1"
  Password: "1234"
  Key: ""
  KeyPemPath: "%StreamAsset%/key.pem"
  StreamSetting:
    Connector: nats
    Host: "192.168.0.110"
    Port: 4222

UserInfo:
  Id: 1
  Name: user1
  Title: super
  Level: 1
  Rank: 1
