// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cred.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ULZAsset.ProtoMod {

  /// <summary>Holder for reflection information generated from cred.proto</summary>
  public static partial class CredReflection {

    #region Descriptor
    /// <summary>File descriptor for cred.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CredReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpjcmVkLnByb3RvEgpSb29tU3RhdHVzGg9HYW1lQ3RsdjIucHJvdG8iOQoH",
          "Q3JlZFJlcRIKCgJJcBgBIAEoCRIQCghVc2VybmFtZRgCIAEoCRIQCghQYXNz",
          "d29yZBgDIAEoCSJVCg5DcmVhdGVDcmVkUmVzcBIMCgRjb2RlGAEgASgFEgwK",
          "BGZpbGUYAiABKAwSJwoJZXJyb3JfbXNnGAMgASgLMhQuUm9vbVN0YXR1cy5F",
          "cnJvck1zZyJPCg1DaGVja0NyZWRSZXNwEhUKDXJlc3BvbnNlX2NvZGUYASAB",
          "KAUSJwoJZXJyb3JfbXNnGAIgASgLMhQuUm9vbVN0YXR1cy5FcnJvck1zZzLM",
          "AQoLQ3JlZGl0c0F1dGgSPQoJQ2hlY2tDcmVkEhMuUm9vbVN0YXR1cy5DcmVk",
          "UmVxGhkuUm9vbVN0YXR1cy5DaGVja0NyZWRSZXNwIgASPgoKQ3JlYXRlQ3Jl",
          "ZBITLlJvb21TdGF0dXMuQ3JlZFJlcRoZLlJvb21TdGF0dXMuQ2hlY2tDcmVk",
          "UmVzcCIAEj4KB0dldENyZWQSEy5Sb29tU3RhdHVzLkNyZWRSZXEaGi5Sb29t",
          "U3RhdHVzLkNyZWF0ZUNyZWRSZXNwIgAwAUITqgIQUGxheUNsaS5Qcm90b01v",
          "ZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ULZAsset.ProtoMod.CredReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ULZAsset.ProtoMod.CredReq), global::ULZAsset.ProtoMod.CredReq.Parser, new [] { "Ip", "Username", "Password" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ULZAsset.ProtoMod.CreateCredResp), global::ULZAsset.ProtoMod.CreateCredResp.Parser, new [] { "Code", "File", "ErrorMsg" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ULZAsset.ProtoMod.CheckCredResp), global::ULZAsset.ProtoMod.CheckCredResp.Parser, new [] { "ResponseCode", "ErrorMsg" }, null, null, null)
        }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CredReq : pb::IMessage<CredReq> {
    private static readonly pb::MessageParser<CredReq> _parser = new pb::MessageParser<CredReq>(() => new CredReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CredReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ULZAsset.ProtoMod.CredReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredReq(CredReq other) : this() {
      ip_ = other.ip_;
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CredReq Clone() {
      return new CredReq(this);
    }

    /// <summary>Field number for the "Ip" field.</summary>
    public const int IpFieldNumber = 1;
    private string ip_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ip {
      get { return ip_; }
      set {
        ip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CredReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CredReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ip != other.Ip)return false;
      if (Username != other.Username)return false;
      if (Password != other.Password)return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Ip.Length != 0)hash ^= Ip.GetHashCode();
      if (Username.Length != 0)hash ^= Username.GetHashCode();
      if (Password.Length != 0)hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Ip.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ip);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Ip.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ip);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CredReq other) {
      if (other == null) {
        return;
      }
      if (other.Ip.Length != 0) {
        Ip = other.Ip;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch (tag) {
          default : _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
          case 10:
            {
              Ip = input.ReadString();
              break;
            }
          case 18:
            {
              Username = input.ReadString();
              break;
            }
          case 26:
            {
              Password = input.ReadString();
              break;
            }
        }
      }
    }

  }

  public sealed partial class CreateCredResp : pb::IMessage<CreateCredResp> {
    private static readonly pb::MessageParser<CreateCredResp> _parser = new pb::MessageParser<CreateCredResp>(() => new CreateCredResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateCredResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ULZAsset.ProtoMod.CredReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateCredResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateCredResp(CreateCredResp other) : this() {
      code_ = other.code_;
      file_ = other.file_;
      errorMsg_ = other.errorMsg_ != null ? other.errorMsg_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateCredResp Clone() {
      return new CreateCredResp(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "file" field.</summary>
    public const int FileFieldNumber = 2;
    private pb::ByteString file_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString File {
      get { return file_; }
      set {
        file_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error_msg" field.</summary>
    public const int ErrorMsgFieldNumber = 3;
    private global::ULZAsset.ProtoMod.ErrorMsg errorMsg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ULZAsset.ProtoMod.ErrorMsg ErrorMsg {
      get { return errorMsg_; }
      set {
        errorMsg_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateCredResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateCredResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code)return false;
      if (File != other.File)return false;
      if (!object.Equals(ErrorMsg, other.ErrorMsg))return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0)hash ^= Code.GetHashCode();
      if (File.Length != 0)hash ^= File.GetHashCode();
      if (errorMsg_ != null)hash ^= ErrorMsg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (File.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(File);
      }
      if (errorMsg_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ErrorMsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (File.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(File);
      }
      if (errorMsg_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ErrorMsg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateCredResp other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.File.Length != 0) {
        File = other.File;
      }
      if (other.errorMsg_ != null) {
        if (errorMsg_ == null) {
          ErrorMsg = new global::ULZAsset.ProtoMod.ErrorMsg();
        }
        ErrorMsg.MergeFrom(other.ErrorMsg);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch (tag) {
          default : _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
          case 8:
            {
              Code = input.ReadInt32();
              break;
            }
          case 18:
            {
              File = input.ReadBytes();
              break;
            }
          case 26:
            {
              if (errorMsg_ == null) {
                ErrorMsg = new global::ULZAsset.ProtoMod.ErrorMsg();
              }
              input.ReadMessage(ErrorMsg);
              break;
            }
        }
      }
    }

  }

  public sealed partial class CheckCredResp : pb::IMessage<CheckCredResp> {
    private static readonly pb::MessageParser<CheckCredResp> _parser = new pb::MessageParser<CheckCredResp>(() => new CheckCredResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CheckCredResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ULZAsset.ProtoMod.CredReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckCredResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckCredResp(CheckCredResp other) : this() {
      responseCode_ = other.responseCode_;
      errorMsg_ = other.errorMsg_ != null ? other.errorMsg_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CheckCredResp Clone() {
      return new CheckCredResp(this);
    }

    /// <summary>Field number for the "response_code" field.</summary>
    public const int ResponseCodeFieldNumber = 1;
    private int responseCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ResponseCode {
      get { return responseCode_; }
      set {
        responseCode_ = value;
      }
    }

    /// <summary>Field number for the "error_msg" field.</summary>
    public const int ErrorMsgFieldNumber = 2;
    private global::ULZAsset.ProtoMod.ErrorMsg errorMsg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ULZAsset.ProtoMod.ErrorMsg ErrorMsg {
      get { return errorMsg_; }
      set {
        errorMsg_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CheckCredResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CheckCredResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseCode != other.ResponseCode)return false;
      if (!object.Equals(ErrorMsg, other.ErrorMsg))return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseCode != 0)hash ^= ResponseCode.GetHashCode();
      if (errorMsg_ != null)hash ^= ErrorMsg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ResponseCode);
      }
      if (errorMsg_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ErrorMsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResponseCode);
      }
      if (errorMsg_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ErrorMsg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CheckCredResp other) {
      if (other == null) {
        return;
      }
      if (other.ResponseCode != 0) {
        ResponseCode = other.ResponseCode;
      }
      if (other.errorMsg_ != null) {
        if (errorMsg_ == null) {
          ErrorMsg = new global::ULZAsset.ProtoMod.ErrorMsg();
        }
        ErrorMsg.MergeFrom(other.ErrorMsg);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch (tag) {
          default : _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
          case 8:
            {
              ResponseCode = input.ReadInt32();
              break;
            }
          case 18:
            {
              if (errorMsg_ == null) {
                ErrorMsg = new global::ULZAsset.ProtoMod.ErrorMsg();
              }
              input.ReadMessage(ErrorMsg);
              break;
            }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code